### ISSUE TITLE
User Story 1

### ISSUE THREAD

**Issue by irene-1308** [SchoolOfCode/bc17-w4d2-project-id#2]
```[tasklist]
### Tasks
- [x] run and install the application (our Express APP)
- [x] GET request to “http://localhost:3000/”
- [x] check that we get back a response with status code of 200 and text saying “Hello World!”
- [x] check to see that the Node API has also logged the request in the terminal (console.log)
```
