### ISSUE TITLE
E2 US2

### ISSUE THREAD

**Issue by dom-m17** [SchoolOfCode/bc17-w4d2-project-id#5]
```[tasklist]
### Tasks
- [x] Then the API should save the new activity to the activities.json file
- [x] giving it a unique “id” (UUID)
- [x] activity_submitted (time stamp - Date.now())
- [x] Then the the request should succeed, responding with the correct status code and the activity object that I posted as the response body
- [x] If data is missing then the request should fail with an explanation
```
