### ISSUE TITLE
E3 US1

### ISSUE THREAD

**Issue by dom-m17** [SchoolOfCode/bc17-w4d2-project-id#6]
```[tasklist]
### Tasks
- [x] the API should update the activity in the activities.json file that has a matching activity id
- [x] the request should succeed, responding with the correct status code and the activity object that I posted as the response body
- [x] If the put request is invalid (no matching id) the request should fail with correct status code and appropriate message
```
