### ISSUE TITLE
E3 US2

### ISSUE THREAD

**Issue by irene-1308** [SchoolOfCode/bc17-w4d2-project-id#7]
```[tasklist]
### Tasks
- [x] delete the activity that has a matching activity id in the activities.json file
- [x] request should succeed, responding with the correct status code and the deleted activity object in the response body
- [x] API call should fail with the correct response code and a clear error message (response.error)
```
